2024-10-16 16:16:37,511-ERROR-this is zero division error
Traceback (most recent call last):
  File "C:\Users\aariz\AppData\Local\Temp\ipykernel_22572\3748920140.py", line 9, in divide
    return a/b
           ~^~
ZeroDivisionError: division by zero
2024-10-22 12:56:34,217-ERROR-this is zero division error
Traceback (most recent call last):
  File "C:\Users\aariz\AppData\Local\Temp\ipykernel_4956\3748920140.py", line 9, in divide
    return a/b
           ~^~
ZeroDivisionError: division by zero
